// Generated by CoffeeScript 1.11.1
(function() {
  var CheckJadeVersion, Parser, PugInheritance, fs, pkginfo;

  Parser = require('./parser');

  fs = require('fs');

  CheckJadeVersion = require('./version');

  pkginfo = JSON.parse(fs.readFileSync('./package.json', 'utf8'));

  PugInheritance = (function() {
    function PugInheritance(filename, directory, options) {
      var checkJadeVersion, parser;
      checkJadeVersion = new CheckJadeVersion(pkginfo, '1.10.0');
      options.deprecated = checkJadeVersion.deprecated;
      parser = new Parser(filename, directory, options);
      this.tree = parser.tree;
      this.files = parser.files;
      return this;
    }

    return PugInheritance;

  })();

  module.exports = PugInheritance;

}).call(this);
