// Generated by CoffeeScript 1.10.0
(function() {
  var Parser, PugInheritance;

  Parser = require('./parser');

  PugInheritance = (function() {
    function PugInheritance(filename, directory, options) {
      var parser;
      parser = new Parser(filename, directory, options);
      this.tree = parser.tree;
      this.files = parser.files;
      return this;
    }

    return PugInheritance;

  })();

  module.exports = PugInheritance;

}).call(this);
