// Generated by CoffeeScript 1.6.3
(function() {
  var JadeInheritance, Parser;

  Parser = require('./parser');

  JadeInheritance = (function() {
    function JadeInheritance(filename, directory, options) {
      var parser;
      parser = new Parser(filename, directory, options);
      this.tree = parser.tree;
      this.files = parser.files;
      return this;
    }

    return JadeInheritance;

  })();

  module.exports = JadeInheritance;

}).call(this);
