// Generated by CoffeeScript 1.11.1
(function() {
  var CheckJadeVersion, compareVersion, underscore;

  compareVersion = require('semver');

  underscore = require('underscore');

  CheckJadeVersion = (function() {
    function CheckJadeVersion(pkg, versionComparator) {
      var cleanedVersion, key;
      this.dependencies = pkg.dependencies ? pkg.dependencies : {};
      this.devDependencies = pkg.devDependencies ? pkg.devDependencies : {};
      this.allDependencies = underscore.extend(this.dependencies, this.devDependencies);
      this.regex = /\^|\~|<|<\=|\>|\>\=|\=/;
      cleanedVersion = null;
      this.deprecated = false;
      for (key in this.allDependencies) {
        switch (key) {
          case 'jade':
          case 'pug':
          case 'gulp-pug':
          case 'jade-pug':
            cleanedVersion = this.cleanUpVersion(this.allDependencies[key]);
            this.deprecated = compareVersion.lt(versionComparator, cleanedVersion);
        }
      }
      return this.deprecated;
    }

    CheckJadeVersion.prototype.cleanUpVersion = function(version) {
      var cleanedVersion, result;
      result = null;
      cleanedVersion = null;
      if ((result = this.regex.exec(version)) !== null) {
        if (result.index === this.regex.lastIndex) {
          this.regex.lastIndex++;
        }
      }
      if (result && typeof result === 'object') {
        if (version.indexOf(result[0]) !== -1) {
          cleanedVersion = version.replace(result[0], '');
        }
        return cleanedVersion;
      } else {
        return version;
      }
    };

    return CheckJadeVersion;

  })();

  module.exports = CheckJadeVersion;

}).call(this);
